name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    name: Build ${{ matrix.configuration }}

    strategy:
      matrix:
        os: [ windows-latest ]
        configuration: [ Debug, Release ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Build TypeNameInterpretation
      run: dotnet build src --configuration ${{ matrix.configuration }}
    - name: Run Tests
      if: matrix.configuration == 'Debug'
      run: dotnet test src --no-build
    - name: Package TypeNameInterpretation
      if: matrix.configuration == 'Release'
      run: dotnet pack src --no-build --configuration ${{ matrix.configuration }} -p:RepositoryCommit=${{ github.sha }} -p:RepositoryBranch=${{ github.ref }}
    - name: Save Artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: bin\TypeNameInterpretation\${{ matrix.configuration }}\*.nupkg
        if-no-files-found: error

